apps/core/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('logs/', views.LogView.as_view(), name='logs'),
    path('requests/', views.RequestView.as_view(), name='requests'),
]

apps/user_profile/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('edit/', views.EditProfileView.as_view(), name='edit'),
]

key_test/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('apps.user_profile.urls', 'apps.user_profile'), namespace='user_profile')),
    path('', include(('apps.core.urls', 'apps.core'), namespace='core')),
    path('accounts/login/', LoginView.as_view(), name='login'),
    path('accounts/logout/', LogoutView.as_view(), name='logout'),
]

apps/core/models.py
from django.db import models


class Request(models.Model):

    path = models.CharField('Path', max_length=190, db_index=True)
    method = models.CharField('Method', max_length=10)
    time = models.DateTimeField('Request time', db_index=True)
    user = models.CharField('User', max_length=100, db_index=True)
    execution_time = models.DurationField('Execution time')

    class Meta:
        verbose_name = 'Request'
        verbose_name_plural = 'Requests'
        ordering = ['-time']

    def __str__(self):
        return f"{self.time.strftime('%d.%m.%y %H:%M:%S %Z')} {self.method} {self.path}"


class LogLine(models.Model):

    CREATE = "create"
    EDIT = "edit"
    DELETE = "delete"

    LOGGING_TYPES = (
        (CREATE, "Create"),
        (EDIT, "Edit"),
        (DELETE, "Delete"),
    )

    logging_time = models.DateTimeField('Logging time', auto_now_add=True)
    logging_type = models.CharField('Logging type', max_length=6, choices=LOGGING_TYPES, db_index=True)
    logging_text = models.TextField('Logging text')

    class Meta:
        verbose_name = 'Log line'
        verbose_name_plural = 'Log lines'
        ordering = ['-logging_time']

    def __str__(self):
        return f"{self.logging_time.strftime('%d.%m.%y %H:%M:%S %Z')} " \
               f"-- [{self.get_logging_type_display()}] -- {self.logging_text}"

apps/user_profile/models.py
from django.db import models


class Profile(models.Model):
    first_name = models.CharField('First name', max_length=200)
    last_name = models.CharField('Last name', max_length=200)
    date_of_birth = models.DateField('Date of birth')
    biography = models.TextField('Biography')
    contacts = models.ManyToManyField('Profile', blank=True)
    user = models.OneToOneField('auth.User', on_delete=models.CASCADE, related_name='profile')
    last_edit_time = models.DateTimeField('Last change time', blank=True, null=True)
    last_editor_ip = models.GenericIPAddressField('Last editor IP', blank=True, null=True)

    class Meta:
        verbose_name = 'Profile'
        verbose_name_plural = 'Profiles'

    def __str__(self):
        return f'#{self.id} {self.first_name} {self.last_name}'

apps/user_profile/forms.py
from django import forms
from django.utils import timezone

from .models import Profile


class ProfileEditForm(forms.ModelForm):

    class Meta:
        model = Profile
        fields = ('first_name', 'last_name', 'date_of_birth', 'biography', 'contacts',)

    def __init__(self, request, *args, **kwargs):
        self.request = request
        super().__init__(*args, **kwargs)

    def save(self, commit=True):
        object = super().save(commit=False)
        object.last_edit_time = timezone.now()
        object.last_editor_ip = self.get_client_ip()
        object.save()
        self.save_m2m()
        return object

    def get_client_ip(self):
        x_forwarded_for = self.request.META.get('HTTP_X_FORWARDED_FOR')
        if x_forwarded_for:
            ip = x_forwarded_for.split(',')[0]
        else:
            ip = self.request.META.get('REMOTE_ADDR')
        return ip

apps/core/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView

from .models import LogLine, Request


class LogView(LoginRequiredMixin, ListView):
    model = LogLine
    template_name = 'core/logs.html'


class RequestView(LoginRequiredMixin, ListView):
    model = Request
    template_name = 'core/requests.html'

apps/user_profile/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import DetailView, UpdateView

from .forms import ProfileEditForm


class RequestUserProfileMixin:
    def get_object(self, queryset=None):
        profile = None
        if hasattr(self.request.user, 'profile'):
            profile = self.request.user.profile
        return profile


class IndexView(LoginRequiredMixin, RequestUserProfileMixin, DetailView):
    template_name = 'user_profile/index.html'


class EditProfileView(LoginRequiredMixin, RequestUserProfileMixin, UpdateView):
    template_name = 'user_profile/edit_profile.html'
    form_class = ProfileEditForm
    success_url = reverse_lazy('user_profile:index')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({'request': self.request})
        return kwargs

apps/core/templates/core/logs.html
{% extends "base.html" %}

{% block title %}Info logs{% endblock %}

{% block content %}
    <a href="{% url "user_profile:index" %}" class="badge badge-primary"> < Home</a>
    <br>
    <h1>Logs of models manipulations</h1>
    {% for logline in logline_list|slice:":10" %}
        <hr>
        <p>{{ logline.logging_time }} [{{ logline.logging_type }}] -- {{ logline.logging_text }}</p>
        <hr>
    {% endfor %}

{% endblock content %}

apps/core/templates/core/requests.html
{% extends "base.html" %}

{% block title %}Last requests{% endblock %}

{% block content %}
    <a href="{% url "user_profile:index" %}" class="badge badge-primary"> < Home</a>
    <br>
    <h1>List of 10 last requests</h1>
    {% for req in request_list|slice:":10" %}
        <hr>
        <p>{{ req.time }} {{ req.user }} {{ req.method }} {{ req.path }} {{ req.execution_time }}</p>
        <hr>
    {% endfor %}

{% endblock content %}

apps/user_profile/templates/user_profile/edit_profile.html
{% extends "base.html" %}
{% load static widget_tweaks %}

{% block title %}Edit profile of {{ request.user }}{% endblock title %}

{% block styles %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static "user_profile/css/bootstrap-datepicker3.min.css" %}">
{% endblock styles %}

{% block content %}
    <a href="{% url "user_profile:index" %}" class="badge badge-primary"> < Home</a>
    <h1>Edit profile of {{ request.user }}</h1>
    <form method="POST" enctype='multipart/form-data' class="item-form">
    <div class="form-group" style="width: 20%;">
        {% csrf_token %}
        {% for field in form %}
            <p><label>{{ field.label }}</label>{% render_field field class="form-control" %}</p>
        {% endfor %}
        <button class="btn btn-info">Сохранить</button>
        </div>
    </form>
{% endblock content %}

{% block scripts %}
    {{ block.super }}
    <script src="{% static "user_profile/js/bootstrap-datepicker.min.js" %}"></script>
    <script src="{% static "user_profile/locales/bootstrap-datepicker.uk.min.js" %}"></script>
    <script>
        $('#id_date_of_birth').datepicker({
            format: "dd.mm.yyyy",
            todayBtn: true,
            language: "uk",
            daysOfWeekHighlighted: "0,6",
            todayHighlight: true
        });
    </script>
{% endblock scripts %}

apps/user_profile/templates/user_profile/index.html
{% extends "base.html" %}
{% load static core_extras %}

{% block title %}Profile page{% endblock %}

{% block content %}
    {% if profile %}
        <h4>
            <a href="{% url "core:requests" %}" class="badge badge-success">Last 10 http requests</a>
            <a href="{% url "core:logs" %}" class="badge badge-info">Logs of models manipulations</a>
        </h4>
        <h4>
            <a href="{% url "user_profile:edit" %}" class="badge badge-info"><img src="{% static "user_profile/images/pencil.svg" %}"> Edit profile here</a>
            <a href="{% get_admin_url profile %}" class="badge badge-warning"><img src="{% static "user_profile/images/pencil.svg" %}"> Admin edit</a>
        </h4>
        <p>First name: {{ profile.first_name }}</p>
        <p>Last name: {{ profile.last_name }}</p>
        <p>Date of birth: {{ profile.date_of_birth }}</p>
        <p>Biography: {{ profile.biography | linebreaks }}</p>
        <p>Contacts: <br>
            {% for contact in profile.contacts.all %}
                - {{ contact.first_name }} {{ contact.last_name }} <br>
            {% endfor %}
        </p>
    {% else %}
        <div>You have no profile! If you have permissions let's go <a href="{% url 'admin:user_profile_profile_add' %}">create!</a></div>
    {% endif %}
{% endblock content %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %}Hello, World!{% endblock title %}</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% block styles %}
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    {% endblock styles %}
</head>

<body>
<div class="page-header">
    {% if user.is_authenticated %}
        <p class="top-menu">Моё почтение, {{ user.username }}
            <small>(<a href="{% url 'logout' %}?next={{ request.path }}" class="badge badge-danger">Выйти</a>)</small>
        </p>
    {% else %}
        <a href="{% url 'login' %}?next={{ request.path }}"></a>
    {% endif %}
</div>
<div class="container-fluid">
    {% block content %}
    {% endblock content %}
</div>

<footer class="container-fluid">
    {% include "footer.html" %}
</footer>

{% block scripts %}
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
{% endblock scripts %}

</body>
</html>

templates/footer.html
{% now "Y" as current_year %}
{% with copyright_start_year="2018" %}
<br>
&#169; Prontsevych E.V., {% if current_year > copyright_start_year %}{{ copyright_start_year }}&mdash;{% endif %}{{ current_year }}
{% endwith %}